apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-env
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: {{ .Chart.Name }}
data:
  INTERVAL: {{ .Values.mqtt.interval | quote }}
  MQTT_HOST: {{ .Values.mqtt.host | quote }}
  MQTT_PORT: {{ .Values.mqtt.port | quote }}
