apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: mqtt
      port: {{ .Values.service.mqttPort }}
      protocol: TCP
      targetPort: mqtt
    - name: dashboard
      port: {{ .Values.service.dashboardPort }}
      protocol: TCP
      targetPort: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-headless"
  labels:
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
